### ISSUE TITLE
Vibrator always 100% power

### ISSUE THREAD

**Issue by arduino-woman** [metafetish/master-beta-kit#1]
Just got a Master Beta kit, and everything seems to be setup correctly, in theory. Turning on the AA battery pack makes the vibrator turn on to 100% full power.

But after successfully uploading any code to the Arduino, I switch the AA battery pack on, and the vibrator still only ever goes on to 100% full power, no matter what code I upload. What am I missing? Thank you!

**Comment by qdot** [comment]
This is not actually my project, I just archived it here. I've never built it and can't tell you how anything works.

You might want to try a DIY community like KinkyMakers: https://kinkymakers.com
